#!/bin/bash
# TODO add folder flag and verbose

help="Usage: `basename $0` [OPTS]
Process bark recordings for peaks

    -h      show this help message and exit
    -c      continuously process until killed
"

continuous=false

while getopts :ch opt; do
    case $opt in
        h)
            echo "$help"
            exit 0
            ;;
        \?)
            echo "$help"
            exit 1
            ;;
        c)
            continuous=true
            ;;
    esac
done

while [ true ]; do
    if find sounds/*.wav > /dev/null 2>&1; then
        for i in sounds/*.wav; do
            amp=$(sox -t .wav "$i" -n stat 2>&1 | grep "Maximum amplitude" | cut -d ':' -f 2 | tr -d ' ')
            dtime=$(echo "$i" | sed -r "s/[a-z\.\/]//g")
            echo -e "\t\t{" >> bark.txt
            echo -e "\t\t\t\"time\": \"$dtime\"," >> bark.txt
            echo -e "\t\t\t\"volume\": \"$amp\"" >> bark.txt
            echo -e "\t\t}," >> bark.txt
            mv "$i" "$i.done"
        done
    fi

    if [[ $continuous == false ]]; then
        exit 0;
    fi

    sleep 1;
done
